/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.logcliente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZAIR
 */
public class dialogpvcliente extends java.awt.Dialog {

    /**
     * Creates new form frmpvcliente
     */
    public dialogpvcliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        mostrar("");
        txtbuscar.setText("Introdusca el nombre a buscar");
    }
    public static String accion="";
    void ocultar_columnas(){
    //idclient
    tablaclientes.getColumnModel().getColumn(0).setPreferredWidth(200);
     //Columna nombre
    tablaclientes.getColumnModel().getColumn(1).setPreferredWidth(300);
     //Columna apellidos
    tablaclientes.getColumnModel().getColumn(2).setPreferredWidth(300);
     //Columna TElefono
    tablaclientes.getColumnModel().getColumn(3).setMaxWidth(0);
    tablaclientes.getColumnModel().getColumn(3).setMinWidth(0);
    tablaclientes.getColumnModel().getColumn(3).setPreferredWidth(0);
      //Columna TElefono
    tablaclientes.getColumnModel().getColumn(4).setMaxWidth(0);
    tablaclientes.getColumnModel().getColumn(4).setMinWidth(0);
    tablaclientes.getColumnModel().getColumn(4).setPreferredWidth(0);
      //Columna rfc
    tablaclientes.getColumnModel().getColumn(5).setMaxWidth(0);
    tablaclientes.getColumnModel().getColumn(5).setMinWidth(0);
    tablaclientes.getColumnModel().getColumn(5).setPreferredWidth(0);
    //Columna Negocio
    tablaclientes.getColumnModel().getColumn(6).setPreferredWidth(600);
         //Columna RFC
    tablaclientes.getColumnModel().getColumn(7).setMaxWidth(0);
    tablaclientes.getColumnModel().getColumn(7).setMinWidth(0);
    tablaclientes.getColumnModel().getColumn(7).setPreferredWidth(0);
    //Columna calle
    tablaclientes.getColumnModel().getColumn(8).setMaxWidth(0);
    tablaclientes.getColumnModel().getColumn(8).setMinWidth(0);
    tablaclientes.getColumnModel().getColumn(8).setPreferredWidth(0);
       //Columna poblacion
    tablaclientes.getColumnModel().getColumn(9).setMaxWidth(0);
    tablaclientes.getColumnModel().getColumn(9).setMinWidth(0);
    tablaclientes.getColumnModel().getColumn(9).setPreferredWidth(0);
        //Columna codigo postal
    tablaclientes.getColumnModel().getColumn(10).setMaxWidth(0);
    tablaclientes.getColumnModel().getColumn(10).setMinWidth(0);
    tablaclientes.getColumnModel().getColumn(10).setPreferredWidth(0);
       //Columna municipio
    tablaclientes.getColumnModel().getColumn(11).setMaxWidth(0);
    tablaclientes.getColumnModel().getColumn(11).setMinWidth(0);
    tablaclientes.getColumnModel().getColumn(11).setPreferredWidth(0);
       //Columna estado
    tablaclientes.getColumnModel().getColumn(12).setMaxWidth(0);
    tablaclientes.getColumnModel().getColumn(12).setMinWidth(0);
    tablaclientes.getColumnModel().getColumn(12).setPreferredWidth(0);
         //Columna Tipo
    tablaclientes.getColumnModel().getColumn(13).setPreferredWidth(200);
         //Columna Preci0
    tablaclientes.getColumnModel().getColumn(14).setPreferredWidth(200);
  
    }
     
     void mostrar(String buscar){
        try {
            DefaultTableModel modelo;
            logcliente func = new logcliente();
            modelo=func.mostrar(buscar);
            tablaclientes.setModel(modelo);
            ocultar_columnas();
  
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaclientes = new javax.swing.JTable();
        txtbuscar = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        tablaclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaclientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaclientes);

        txtbuscar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtbuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtbuscar.setToolTipText("Tecla intro para buscar");
        txtbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbuscarMouseClicked(evt);
            }
        });
        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void tablaclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaclientesMouseClicked
              if (evt.getClickCount()==2 ) {
                  try {
                      if (accion.equals("Venta")) {
                      int fila= tablaclientes.rowAtPoint(evt.getPoint());
                      frmpuntoventa.lbl_idcliente.setText(tablaclientes.getValueAt(fila, 0).toString());
                      frmpuntoventa.txtcliente.setText(tablaclientes.getValueAt(fila, 1).toString()+" "+tablaclientes.getValueAt(fila, 2).toString()+" - "+tablaclientes.getValueAt(fila, 7).toString());
                      frmpuntoventa.lblnombrecliente.setText(tablaclientes.getValueAt(fila, 1).toString()+" "+(tablaclientes.getValueAt(fila, 2).toString()));
                      frmpuntoventa.lblnombrenegocio.setText(tablaclientes.getValueAt(fila, 7).toString());
                      frmpuntoventa.txtlistaprecio.setText(tablaclientes.getValueAt(fila, 14).toString());
                      this.dispose(); 
                      }
                      if (accion.equals("Venta2")) {
                      int fila= tablaclientes.rowAtPoint(evt.getPoint());
                      frmpuntoventa2.lbl_idcliente.setText(tablaclientes.getValueAt(fila, 0).toString());
                      frmpuntoventa2.txtcliente.setText(tablaclientes.getValueAt(fila, 1).toString()+" "+tablaclientes.getValueAt(fila, 2).toString()+" - "+tablaclientes.getValueAt(fila, 7).toString());
                      frmpuntoventa2.lblnombrecliente.setText(tablaclientes.getValueAt(fila, 1).toString()+" "+(tablaclientes.getValueAt(fila, 2).toString()));
                      frmpuntoventa2.lblnombrenegocio.setText(tablaclientes.getValueAt(fila, 7).toString());
                      frmpuntoventa2.txtlistaprecio.setText(tablaclientes.getValueAt(fila, 14).toString());
                      this.dispose(); 
                      }
                      if (accion.equals("Preventa")) {
                      int fila= tablaclientes.rowAtPoint(evt.getPoint());
                      frmpuntoventa_preventa.lbl_idcliente.setText(tablaclientes.getValueAt(fila, 0).toString());
                      frmpuntoventa_preventa.txtcliente.setText(tablaclientes.getValueAt(fila, 1).toString()+" "+tablaclientes.getValueAt(fila, 2).toString()+" - "+tablaclientes.getValueAt(fila, 7).toString());
                      frmpuntoventa_preventa.lblnombrecliente.setText(tablaclientes.getValueAt(fila, 1).toString()+" "+(tablaclientes.getValueAt(fila, 2).toString()));
                      frmpuntoventa_preventa.lblnombrenegocio.setText(tablaclientes.getValueAt(fila, 7).toString());
                      frmpuntoventa_preventa.txtlistaprecio.setText(tablaclientes.getValueAt(fila, 14).toString());
                      this.dispose(); 
                      }
                        if (accion.equals("Equipaje")) {
                      int fila= tablaclientes.rowAtPoint(evt.getPoint());
                      frmpv_equipaje.lbl_idcliente.setText(tablaclientes.getValueAt(fila, 0).toString());
                      frmpv_equipaje.txtcliente.setText(tablaclientes.getValueAt(fila, 1).toString()+" "+tablaclientes.getValueAt(fila, 2).toString()+" - "+tablaclientes.getValueAt(fila, 7).toString());
                      frmpv_equipaje.lblnombrecliente.setText(tablaclientes.getValueAt(fila, 1).toString()+" "+(tablaclientes.getValueAt(fila, 2).toString()));
                      frmpv_equipaje.lblnombrenegocio.setText(tablaclientes.getValueAt(fila, 7).toString());
                      frmpv_equipaje.txtlistaprecio.setText(tablaclientes.getValueAt(fila, 14).toString());
                      this.dispose();
                       }
                      
                  } catch (Exception e) {
                  }
              }
    }//GEN-LAST:event_tablaclientesMouseClicked

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        mostrar(txtbuscar.getText());
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbuscarMouseClicked
       txtbuscar.setText("");
    }//GEN-LAST:event_txtbuscarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialogpvcliente dialog = new dialogpvcliente(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaclientes;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
