/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.logcliente;
import Logica.logproveedor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZAIR
 */
public class dialogproveedor extends java.awt.Dialog {

    /**
     * Creates new form frmpvcliente
     */
    public dialogproveedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        mostrar("");
    }
     void ocultar_columnas(){
    tablaproveedores.getColumnModel().getColumn(0).setMaxWidth(0);
    tablaproveedores.getColumnModel().getColumn(0).setMinWidth(0);
    tablaproveedores.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
     void mostrar(String buscar){
        try {
            DefaultTableModel modelo;
            logproveedor func = new logproveedor();
            modelo=func.mostrar(buscar);
            tablaproveedores.setModel(modelo);
            ocultar_columnas();
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaproveedores = new javax.swing.JTable();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        tablaproveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaproveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaproveedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaproveedores);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void tablaproveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaproveedoresMouseClicked
              if (evt.getClickCount()==2 ) {
                  try {
                      int fila= tablaproveedores.rowAtPoint(evt.getPoint());
                      frmpuntocompra.lbl_idproveedor.setText(tablaproveedores.getValueAt(fila, 0).toString());
                      frmpuntocompra.txtproveedor.setText(tablaproveedores.getValueAt(fila, 1).toString());
                      frmpuntocompra.lbl_nombreproveedor.setText(tablaproveedores.getValueAt(fila, 1).toString());
                      frmpuntocompra.lbl_representante.setText(tablaproveedores.getValueAt(fila, 6).toString());
                      this.dispose();
                  } catch (Exception e) {
                  }
              }
    }//GEN-LAST:event_tablaproveedoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialogproveedor dialog = new dialogproveedor(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaproveedores;
    // End of variables declaration//GEN-END:variables
}
