/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import Logica.logcommon;
import java.awt.Color;
import javax.swing.JInternalFrame;

/**
 *
 * @author ZAIR
 */
public class frminicio extends javax.swing.JFrame {

    /**
     * Creates new form frminicio
     */
    public frminicio() {
        initComponents();
        //Maximizando
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("PUNTO DE VENTA LA TERMINAL");
        lblidTrab.setVisible(true);
        lblidcaja.setText(idcaja);
        lblnombretrabajador.setText(nombretrabajador);
        //Coloreando
        Color CPrincipal = logcommon.ColorPrincipal();
        escritorio.setBackground(CPrincipal);
        
    }

    //Declarando variable
    public  static ImageIcon logo,imagenagua;
    public static String idtrabajador;
    public static String nombretrabajador;
    public static String idcaja;
    //Declarando objetos principales
    frmpuntoventa puntoventa1 = new frmpuntoventa();
    frmpuntoventa2 puntoventa2 = new frmpuntoventa2();
    frmpuntoventa_preventa puntopreventa = new frmpuntoventa_preventa();
    frmpuntocompra puntocompra = new frmpuntocompra();
    frmarticulolistado articuloslistado = new frmarticulolistado();
    public frmclientelistado clienteslistado = new frmclientelistado();
    public frmproveedorlistado proveedoreslistado = new frmproveedorlistado();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lbltexttranajador1 = new javax.swing.JLabel();
        lblnombretrabajador = new javax.swing.JLabel();
        lblidTrab = new javax.swing.JLabel();
        txtbienvenido = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbltextcaja = new javax.swing.JLabel();
        lblidcaja = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuptoventa = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        mnuptoventa2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnuoperaciones = new javax.swing.JMenu();
        menuclientes = new javax.swing.JMenuItem();
        mnucompras = new javax.swing.JMenuItem();
        productosMenuItem = new javax.swing.JMenuItem();
        mnuproveedores = new javax.swing.JMenuItem();
        mnuusuarios = new javax.swing.JMenuItem();
        menureportes = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        menuventasxrango = new javax.swing.JMenuItem();
        mnuventasxidaadmin = new javax.swing.JMenuItem();
        menuventasxrango1 = new javax.swing.JMenuItem();
        mnuventasxida2 = new javax.swing.JMenuItem();
        menucompras = new javax.swing.JMenu();
        mnuventasxida1 = new javax.swing.JMenuItem();
        menureportesdeutilidad = new javax.swing.JMenu();
        menuutilidadxrangoxarticulo = new javax.swing.JMenuItem();
        menureportesdecomision = new javax.swing.JMenu();
        menucomisionxrango = new javax.swing.JMenuItem();
        menusugeridocompras = new javax.swing.JMenuItem();
        menuexistencias = new javax.swing.JMenuItem();
        menuprecios = new javax.swing.JMenuItem();
        menuvalorinventario = new javax.swing.JMenuItem();
        menuguardaequipaje = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        menuutilerias = new javax.swing.JMenu();
        menualtaexpress = new javax.swing.JMenuItem();
        menucortecaja = new javax.swing.JMenuItem();
        menuinventario = new javax.swing.JMenuItem();
        menuinventario1 = new javax.swing.JMenuItem();
        menucortecaja1 = new javax.swing.JMenuItem();
        menuadmoncaja = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        escritorio.setBackground(new java.awt.Color(255, 255, 255));
        escritorio.setForeground(new java.awt.Color(255, 255, 255));
        escritorio.setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbltexttranajador1.setBackground(new java.awt.Color(255, 255, 255));
        lbltexttranajador1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbltexttranajador1.setForeground(new java.awt.Color(3, 79, 132));
        lbltexttranajador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltexttranajador1.setText("SISTEMA DE ADMINISTRACION");

        lblnombretrabajador.setBackground(new java.awt.Color(255, 255, 255));
        lblnombretrabajador.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblnombretrabajador.setForeground(new java.awt.Color(3, 79, 132));
        lblnombretrabajador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnombretrabajador.setText("lblnombretrabajador");

        lblidTrab.setText("idtrabajador");

        txtbienvenido.setBackground(new java.awt.Color(255, 255, 255));
        txtbienvenido.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtbienvenido.setForeground(new java.awt.Color(3, 79, 132));
        txtbienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtbienvenido.setText("BIENVENIDO");
        txtbienvenido.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbltextcaja.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbltextcaja.setForeground(new java.awt.Color(3, 79, 132));
        lbltextcaja.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbltextcaja.setText("CAJA:");

        lblidcaja.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblidcaja.setForeground(new java.awt.Color(3, 79, 132));
        lblidcaja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblidcaja.setText("IDCAJA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(lbltextcaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblidcaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidcaja)
                    .addComponent(lbltextcaja, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logo/splash.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbltexttranajador1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
            .addComponent(lblnombretrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblidTrab, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtbienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblidTrab, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(lbltexttranajador1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblnombretrabajador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(txtbienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(425, Short.MAX_VALUE)))
        );

        escritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio);

        menuBar.setBackground(new java.awt.Color(3, 79, 132));
        menuBar.setForeground(new java.awt.Color(255, 255, 255));
        menuBar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuBar.setMaximumSize(new java.awt.Dimension(700, 32769));
        menuBar.setPreferredSize(new java.awt.Dimension(629, 74));

        mnuptoventa.setBackground(new java.awt.Color(3, 79, 132));
        mnuptoventa.setBorder(null);
        mnuptoventa.setForeground(new java.awt.Color(255, 255, 255));
        mnuptoventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Shopping_Cart_32px_1.png"))); // NOI18N
        mnuptoventa.setMnemonic('e');
        mnuptoventa.setText("VENTAS");
        mnuptoventa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mnuptoventa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mnuptoventa.setOpaque(true);
        mnuptoventa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuptoventaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuptoventaMouseEntered(evt);
            }
        });
        mnuptoventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuptoventaActionPerformed(evt);
            }
        });

        jMenuItem5.setBackground(mnuptoventa.getBackground());
        jMenuItem5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem5.setForeground(java.awt.Color.white);
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Rent_32px.png"))); // NOI18N
        jMenuItem5.setText("PUNTO DE VENTA");
        jMenuItem5.setOpaque(true);
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnuptoventa.add(jMenuItem5);

        jMenuItem2.setBackground(mnuptoventa.getBackground());
        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem2.setForeground(java.awt.Color.white);
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Currency_Exchange_32px.png"))); // NOI18N
        jMenuItem2.setText("DEVOLUCIONES");
        jMenuItem2.setOpaque(true);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuptoventa.add(jMenuItem2);

        jMenuItem6.setBackground(mnuptoventa.getBackground());
        jMenuItem6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem6.setForeground(java.awt.Color.white);
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Rent_32px.png"))); // NOI18N
        jMenuItem6.setText("PUNTO DE VENTA 2");
        jMenuItem6.setOpaque(true);
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnuptoventa.add(jMenuItem6);

        mnuptoventa2.setBackground(mnuptoventa.getBackground());
        mnuptoventa2.setBorder(null);
        mnuptoventa2.setForeground(new java.awt.Color(255, 255, 255));
        mnuptoventa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Shopping_Cart_32px_1.png"))); // NOI18N
        mnuptoventa2.setMnemonic('e');
        mnuptoventa2.setText("PREVENTAS");
        mnuptoventa2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mnuptoventa2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mnuptoventa2.setOpaque(true);
        mnuptoventa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuptoventa2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuptoventa2MouseEntered(evt);
            }
        });
        mnuptoventa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuptoventa2ActionPerformed(evt);
            }
        });

        jMenuItem7.setBackground(mnuptoventa.getBackground());
        jMenuItem7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem7.setForeground(java.awt.Color.white);
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Rent_32px.png"))); // NOI18N
        jMenuItem7.setText("PREVENTA");
        jMenuItem7.setOpaque(true);
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mnuptoventa2.add(jMenuItem7);

        jMenuItem3.setBackground(mnuptoventa.getBackground());
        jMenuItem3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem3.setForeground(java.awt.Color.white);
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Currency_Exchange_32px.png"))); // NOI18N
        jMenuItem3.setText("CONSULTA PREVENTAS");
        jMenuItem3.setOpaque(true);
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnuptoventa2.add(jMenuItem3);

        mnuptoventa.add(mnuptoventa2);

        jMenuItem4.setBackground(mnuptoventa.getBackground());
        jMenuItem4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Suitcase_32px.png"))); // NOI18N
        jMenuItem4.setText("GUARDA EQUIPAJE");
        jMenuItem4.setOpaque(true);
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnuptoventa.add(jMenuItem4);

        menuBar.add(mnuptoventa);

        mnuoperaciones.setBackground(mnuptoventa.getBackground());
        mnuoperaciones.setForeground(new java.awt.Color(255, 255, 255));
        mnuoperaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Work_32px.png"))); // NOI18N
        mnuoperaciones.setMnemonic('h');
        mnuoperaciones.setText("OPERACIONES");
        mnuoperaciones.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mnuoperaciones.setOpaque(true);

        menuclientes.setBackground(mnuptoventa.getBackground());
        menuclientes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuclientes.setForeground(new java.awt.Color(255, 255, 255));
        menuclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_client.png"))); // NOI18N
        menuclientes.setText("CLIENTES");
        menuclientes.setOpaque(true);
        menuclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuclientesActionPerformed(evt);
            }
        });
        mnuoperaciones.add(menuclientes);

        mnucompras.setBackground(mnuptoventa.getBackground());
        mnucompras.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mnucompras.setForeground(new java.awt.Color(255, 255, 255));
        mnucompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Shopping_Bag_32px.png"))); // NOI18N
        mnucompras.setText("COMPRAS");
        mnucompras.setOpaque(true);
        mnucompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnucomprasActionPerformed(evt);
            }
        });
        mnuoperaciones.add(mnucompras);

        productosMenuItem.setBackground(mnuptoventa.getBackground());
        productosMenuItem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        productosMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        productosMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_QR_Code_32px.png"))); // NOI18N
        productosMenuItem.setMnemonic('c');
        productosMenuItem.setText("PRODUCTOS");
        productosMenuItem.setOpaque(true);
        productosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosMenuItemActionPerformed(evt);
            }
        });
        mnuoperaciones.add(productosMenuItem);

        mnuproveedores.setBackground(mnuptoventa.getBackground());
        mnuproveedores.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mnuproveedores.setForeground(new java.awt.Color(255, 255, 255));
        mnuproveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_proveedor.png"))); // NOI18N
        mnuproveedores.setText("PROVEEDORES");
        mnuproveedores.setOpaque(true);
        mnuproveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuproveedoresMouseClicked(evt);
            }
        });
        mnuproveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuproveedoresActionPerformed(evt);
            }
        });
        mnuoperaciones.add(mnuproveedores);

        mnuusuarios.setBackground(mnuptoventa.getBackground());
        mnuusuarios.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mnuusuarios.setForeground(new java.awt.Color(255, 255, 255));
        mnuusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_users.png"))); // NOI18N
        mnuusuarios.setMnemonic('a');
        mnuusuarios.setText("USUARIOS");
        mnuusuarios.setOpaque(true);
        mnuusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuusuariosMouseClicked(evt);
            }
        });
        mnuusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuusuariosActionPerformed(evt);
            }
        });
        mnuoperaciones.add(mnuusuarios);

        menuBar.add(mnuoperaciones);

        menureportes.setBackground(mnuptoventa.getBackground());
        menureportes.setForeground(new java.awt.Color(255, 255, 255));
        menureportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Purchase_Order_32px.png"))); // NOI18N
        menureportes.setText("REPORTES");
        menureportes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menureportes.setOpaque(true);

        jMenu4.setBackground(mnuptoventa.getBackground());
        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Purchase_Order_32px.png"))); // NOI18N
        jMenu4.setText("REPORTES DE VENTAS");
        jMenu4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenu4.setOpaque(true);
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });

        menuventasxrango.setBackground(mnuptoventa.getBackground());
        menuventasxrango.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuventasxrango.setForeground(new java.awt.Color(255, 255, 255));
        menuventasxrango.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_News_32px_1.png"))); // NOI18N
        menuventasxrango.setText("VENTAS X RANGO");
        menuventasxrango.setOpaque(true);
        menuventasxrango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuventasxrangoActionPerformed(evt);
            }
        });
        jMenu4.add(menuventasxrango);

        mnuventasxidaadmin.setBackground(mnuptoventa.getBackground());
        mnuventasxidaadmin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mnuventasxidaadmin.setForeground(new java.awt.Color(255, 255, 255));
        mnuventasxidaadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Transaction_List_32px.png"))); // NOI18N
        mnuventasxidaadmin.setText("VENTAS X DIA ADMIN");
        mnuventasxidaadmin.setOpaque(true);
        mnuventasxidaadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuventasxidaadminActionPerformed(evt);
            }
        });
        jMenu4.add(mnuventasxidaadmin);

        menuventasxrango1.setBackground(mnuptoventa.getBackground());
        menuventasxrango1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuventasxrango1.setForeground(new java.awt.Color(255, 255, 255));
        menuventasxrango1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_News_32px_1.png"))); // NOI18N
        menuventasxrango1.setText("VENTAS X RANGO X TRABAJADOR");
        menuventasxrango1.setOpaque(true);
        menuventasxrango1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuventasxrango1ActionPerformed(evt);
            }
        });
        jMenu4.add(menuventasxrango1);

        mnuventasxida2.setBackground(mnuptoventa.getBackground());
        mnuventasxida2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mnuventasxida2.setForeground(new java.awt.Color(255, 255, 255));
        mnuventasxida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Transaction_List_32px.png"))); // NOI18N
        mnuventasxida2.setText("VENTAS X DIA");
        mnuventasxida2.setOpaque(true);
        mnuventasxida2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuventasxida2ActionPerformed(evt);
            }
        });
        jMenu4.add(mnuventasxida2);

        menureportes.add(jMenu4);

        menucompras.setBackground(mnuptoventa.getBackground());
        menucompras.setForeground(new java.awt.Color(255, 255, 255));
        menucompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Purchase_Order_32px.png"))); // NOI18N
        menucompras.setText("REPORTES DE COMPRAS");
        menucompras.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menucompras.setOpaque(true);
        menucompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menucomprasMouseClicked(evt);
            }
        });

        mnuventasxida1.setBackground(mnuptoventa.getBackground());
        mnuventasxida1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mnuventasxida1.setForeground(new java.awt.Color(255, 255, 255));
        mnuventasxida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Transaction_List_32px.png"))); // NOI18N
        mnuventasxida1.setText("COMPRAS X DIA");
        mnuventasxida1.setOpaque(true);
        mnuventasxida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuventasxida1ActionPerformed(evt);
            }
        });
        menucompras.add(mnuventasxida1);

        menureportes.add(menucompras);

        menureportesdeutilidad.setBackground(mnuptoventa.getBackground());
        menureportesdeutilidad.setForeground(new java.awt.Color(255, 255, 255));
        menureportesdeutilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Paper_Money_32px_1.png"))); // NOI18N
        menureportesdeutilidad.setText("REPORTES DE UTILIDAD");
        menureportesdeutilidad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menureportesdeutilidad.setOpaque(true);
        menureportesdeutilidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menureportesdeutilidadMouseClicked(evt);
            }
        });

        menuutilidadxrangoxarticulo.setBackground(mnuptoventa.getBackground());
        menuutilidadxrangoxarticulo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuutilidadxrangoxarticulo.setForeground(new java.awt.Color(255, 255, 255));
        menuutilidadxrangoxarticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_News_32px_1.png"))); // NOI18N
        menuutilidadxrangoxarticulo.setText("UTILIDAD X RANGO X ARTICULO");
        menuutilidadxrangoxarticulo.setOpaque(true);
        menuutilidadxrangoxarticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuutilidadxrangoxarticuloActionPerformed(evt);
            }
        });
        menureportesdeutilidad.add(menuutilidadxrangoxarticulo);

        menureportes.add(menureportesdeutilidad);

        menureportesdecomision.setBackground(mnuptoventa.getBackground());
        menureportesdecomision.setForeground(new java.awt.Color(255, 255, 255));
        menureportesdecomision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Paper_Money_32px_1.png"))); // NOI18N
        menureportesdecomision.setText("REPORTES DE COMISION");
        menureportesdecomision.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menureportesdecomision.setOpaque(true);
        menureportesdecomision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menureportesdecomisionMouseClicked(evt);
            }
        });

        menucomisionxrango.setBackground(mnuptoventa.getBackground());
        menucomisionxrango.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menucomisionxrango.setForeground(new java.awt.Color(255, 255, 255));
        menucomisionxrango.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_News_32px_1.png"))); // NOI18N
        menucomisionxrango.setText("COMISION X RANGO");
        menucomisionxrango.setOpaque(true);
        menucomisionxrango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucomisionxrangoActionPerformed(evt);
            }
        });
        menureportesdecomision.add(menucomisionxrango);

        menureportes.add(menureportesdecomision);

        menusugeridocompras.setBackground(mnuptoventa.getBackground());
        menusugeridocompras.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menusugeridocompras.setForeground(new java.awt.Color(255, 255, 255));
        menusugeridocompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Trolley_32px.png"))); // NOI18N
        menusugeridocompras.setText("SUGERIDO DE COMPRAS");
        menusugeridocompras.setOpaque(true);
        menusugeridocompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusugeridocomprasActionPerformed(evt);
            }
        });
        menureportes.add(menusugeridocompras);

        menuexistencias.setBackground(mnuptoventa.getBackground());
        menuexistencias.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuexistencias.setForeground(new java.awt.Color(255, 255, 255));
        menuexistencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_View_Details_32px.png"))); // NOI18N
        menuexistencias.setText("CATALOGO EXISTENCIAS");
        menuexistencias.setOpaque(true);
        menuexistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuexistenciasActionPerformed(evt);
            }
        });
        menureportes.add(menuexistencias);

        menuprecios.setBackground(mnuptoventa.getBackground());
        menuprecios.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuprecios.setForeground(new java.awt.Color(255, 255, 255));
        menuprecios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_General_Ledger_32px.png"))); // NOI18N
        menuprecios.setText("CATALOGO PRECIOS");
        menuprecios.setOpaque(true);
        menuprecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupreciosActionPerformed(evt);
            }
        });
        menureportes.add(menuprecios);

        menuvalorinventario.setBackground(mnuptoventa.getBackground());
        menuvalorinventario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuvalorinventario.setForeground(new java.awt.Color(255, 255, 255));
        menuvalorinventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Scatter_Plot_32px.png"))); // NOI18N
        menuvalorinventario.setText("VALOR INVENTARIO");
        menuvalorinventario.setOpaque(true);
        menuvalorinventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuvalorinventarioActionPerformed(evt);
            }
        });
        menureportes.add(menuvalorinventario);

        menuguardaequipaje.setBackground(mnuptoventa.getBackground());
        menuguardaequipaje.setForeground(new java.awt.Color(255, 255, 255));
        menuguardaequipaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_About_32px_2.png"))); // NOI18N
        menuguardaequipaje.setText("GUARDAEQUIPAJE");
        menuguardaequipaje.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuguardaequipaje.setOpaque(true);
        menuguardaequipaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuguardaequipajeMouseClicked(evt);
            }
        });

        jMenuItem8.setBackground(mnuptoventa.getBackground());
        jMenuItem8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem8.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_News_32px_1.png"))); // NOI18N
        jMenuItem8.setText("REPORTE DE GUARDAEQUIPAGE");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menuguardaequipaje.add(jMenuItem8);

        jMenuItem9.setBackground(mnuptoventa.getBackground());
        jMenuItem9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem9.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_News_32px_1.png"))); // NOI18N
        jMenuItem9.setText("REPORTE DE GUARDAEQUIPAGE X TRABAJADOR");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        menuguardaequipaje.add(jMenuItem9);

        menureportes.add(menuguardaequipaje);

        menuBar.add(menureportes);

        menuutilerias.setBackground(mnuptoventa.getBackground());
        menuutilerias.setForeground(new java.awt.Color(255, 255, 255));
        menuutilerias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Briefcase_32px.png"))); // NOI18N
        menuutilerias.setText("UTILIERIAS");
        menuutilerias.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuutilerias.setOpaque(true);

        menualtaexpress.setBackground(mnuptoventa.getBackground());
        menualtaexpress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menualtaexpress.setForeground(new java.awt.Color(255, 255, 255));
        menualtaexpress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Add_New_32px.png"))); // NOI18N
        menualtaexpress.setText("ALTA EXPRES");
        menualtaexpress.setOpaque(true);
        menualtaexpress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menualtaexpressActionPerformed(evt);
            }
        });
        menuutilerias.add(menualtaexpress);

        menucortecaja.setBackground(mnuptoventa.getBackground());
        menucortecaja.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menucortecaja.setForeground(new java.awt.Color(255, 255, 255));
        menucortecaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Coin_32px.png"))); // NOI18N
        menucortecaja.setText("CORTE DE CAJA");
        menucortecaja.setOpaque(true);
        menucortecaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucortecajaActionPerformed(evt);
            }
        });
        menuutilerias.add(menucortecaja);

        menuinventario.setBackground(mnuptoventa.getBackground());
        menuinventario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuinventario.setForeground(new java.awt.Color(255, 255, 255));
        menuinventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Calculator_32px.png"))); // NOI18N
        menuinventario.setText("MODIFICAR INVENTARIO");
        menuinventario.setOpaque(true);
        menuinventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuinventarioActionPerformed(evt);
            }
        });
        menuutilerias.add(menuinventario);

        menuinventario1.setBackground(mnuptoventa.getBackground());
        menuinventario1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuinventario1.setForeground(new java.awt.Color(255, 255, 255));
        menuinventario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Calculator_32px.png"))); // NOI18N
        menuinventario1.setText("SELECIONAR IMPRESORAS");
        menuinventario1.setOpaque(true);
        menuinventario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuinventario1ActionPerformed(evt);
            }
        });
        menuutilerias.add(menuinventario1);

        menucortecaja1.setBackground(mnuptoventa.getBackground());
        menucortecaja1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menucortecaja1.setForeground(new java.awt.Color(255, 255, 255));
        menucortecaja1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_Coin_32px.png"))); // NOI18N
        menucortecaja1.setText("GASTOS");
        menucortecaja1.setOpaque(true);
        menucortecaja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucortecaja1ActionPerformed(evt);
            }
        });
        menuutilerias.add(menucortecaja1);

        menuadmoncaja.setBackground(mnuptoventa.getBackground());
        menuadmoncaja.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuadmoncaja.setForeground(new java.awt.Color(255, 255, 255));
        menuadmoncaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_General_Ledger_32px.png"))); // NOI18N
        menuadmoncaja.setText("ADMINISTRACION CAJA");
        menuadmoncaja.setOpaque(true);
        menuadmoncaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuadmoncajaActionPerformed(evt);
            }
        });
        menuutilerias.add(menuadmoncaja);

        menuBar.add(menuutilerias);

        jMenu2.setBackground(mnuptoventa.getBackground());
        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/32x32/icons8_About_32px_2.png"))); // NOI18N
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenu2.setOpaque(true);
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Con este metodo controlamos si ya se mostro una ventana interna
    //En caso de que sea si se muestra al frente, si no se abre
public void ControlaInstancia(JInternalFrame inter){
 
boolean mostrar=true;
String Nombre=inter.getTitle();
for (int a=0;a<escritorio.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
    if( inter.getClass().isInstance( escritorio.getComponent(a) )){
        JOptionPane.showMessageDialog(rootPane, "La ventana "+Nombre+" que interta abrir ya está abierta, cierre la ventana actual e intente nuevamente");
        System.out.println("esta instancia, no se debe mostrar");
        inter.toFront();
        escritorio.moveToFront(inter);
        mostrar=false;
 
    }else{
        System.out.println("no lo es, puede mostrarse");
    }
}
if(mostrar){
    
    Dimension desktopSize = escritorio.getSize();
    inter.setSize(escritorio.getSize());
    escritorio.add(inter);
}
inter.show();
 
 
}
    
    private void mnuusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuusuariosMouseClicked
    
        
              // TODO add your handling code here:
    }//GEN-LAST:event_mnuusuariosMouseClicked

    private void menuclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuclientesActionPerformed
    try {
          boolean mostrar=true;
          
          String Nombre=clienteslistado.getTitle();
          for (int a=0;a<escritorio.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
          if( clienteslistado.getClass().isInstance( escritorio.getComponent(a) )){
       // JOptionPane.showMessageDialog(rootPane, "La ventana "+Nombre+" que interta abrir ya está abierta, cierre la ventana actual e intente nuevamente");
        System.out.println("esta instancia, no se debe mostrar");
        clienteslistado.toFront();
        clienteslistado.mostrar("");
        escritorio.moveToFront(clienteslistado);
        mostrar=false;
 
    }else{
        System.out.println("no lo es, puede mostrarse");
    }
        }
        if(mostrar){
    
        Dimension desktopSize = escritorio.getSize();
         clienteslistado.setSize(escritorio.getSize());
        escritorio.add(clienteslistado);
        //articuloslistado.setTitle("Farma-Medic Caja "+ lblidcaja.getText()+ "   Le atiende:    "+lblnombretrabajador.getText());
         
          ((javax.swing.plaf.basic.BasicInternalFrameUI)clienteslistado.getUI()).setNorthPane(null);//Con esto quito el title
}
         clienteslistado.show();

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error al mostrar listado de clientes: " + e);
        }
    }//GEN-LAST:event_menuclientesActionPerformed

    private void mnuusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuusuariosActionPerformed
       try {
        frmtrabajadorlista trabajador = new frmtrabajadorlista();
        escritorio.add(trabajador);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = trabajador.getSize();
        trabajador.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        trabajador.toFront();
        trabajador.setVisible(true);  
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error: " + e);
        }
    }//GEN-LAST:event_mnuusuariosActionPerformed

    private void mnuproveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuproveedoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuproveedoresMouseClicked

    private void mnuproveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuproveedoresActionPerformed
         try {
          boolean mostrar=true;
          String Nombre=proveedoreslistado.getTitle();
          for (int a=0;a<escritorio.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
          if( proveedoreslistado.getClass().isInstance( escritorio.getComponent(a) )){
            // JOptionPane.showMessageDialog(rootPane, "La ventana "+Nombre+" que interta abrir ya está abierta, cierre la ventana actual e intente nuevamente");
             System.out.println("esta instancia, no se debe mostrar");
             proveedoreslistado.toFront();
             proveedoreslistado.mostrar("");
             escritorio.moveToFront(proveedoreslistado);
             mostrar=false;
 
    }else{
        System.out.println("no lo es, puede mostrarse");
    }
        }
        if(mostrar){
    
        Dimension desktopSize = escritorio.getSize();
         proveedoreslistado.setSize(escritorio.getSize());
        escritorio.add(proveedoreslistado);
        //articuloslistado.setTitle("Farma-Medic Caja "+ lblidcaja.getText()+ "   Le atiende:    "+lblnombretrabajador.getText());
         
          ((javax.swing.plaf.basic.BasicInternalFrameUI)proveedoreslistado.getUI()).setNorthPane(null);//Con esto quito el title
}
         proveedoreslistado.show();

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error: " + e);
        }
    }//GEN-LAST:event_mnuproveedoresActionPerformed

    private void productosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosMenuItemActionPerformed
        try {
          boolean mostrar=true;
          
          String Nombre=articuloslistado.getTitle();
          for (int a=0;a<escritorio.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
          if( articuloslistado.getClass().isInstance( escritorio.getComponent(a) )){
       // JOptionPane.showMessageDialog(rootPane, "La ventana "+Nombre+" que interta abrir ya está abierta, cierre la ventana actual e intente nuevamente");
        System.out.println("esta instancia, no se debe mostrar");
        articuloslistado.toFront();
        articuloslistado.mostrar("");
        escritorio.moveToFront(articuloslistado);
        mostrar=false;
 
    }else{
        System.out.println("no lo es, puede mostrarse");
    }
        }
        if(mostrar){
    
        Dimension desktopSize = escritorio.getSize();
         articuloslistado.setSize(escritorio.getSize());
        escritorio.add(articuloslistado);
        //articuloslistado.setTitle("Farma-Medic Caja "+ lblidcaja.getText()+ "   Le atiende:    "+lblnombretrabajador.getText());
         
          ((javax.swing.plaf.basic.BasicInternalFrameUI)articuloslistado.getUI()).setNorthPane(null);//Con esto quito el title
}
         articuloslistado.show();

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error: " + e);
        }
    }//GEN-LAST:event_productosMenuItemActionPerformed

    private void menualtaexpressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menualtaexpressActionPerformed
try {
        frmarticuloxpress ventana = new frmarticuloxpress();
        escritorio.add(ventana);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        ventana.toFront();
       
        ventana.setVisible(true);  
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error: " + e);
        }       
    }//GEN-LAST:event_menualtaexpressActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked

        frm_pruebas ventana = new frm_pruebas();
       ventana.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void menucortecajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucortecajaActionPerformed
      try {
        frmcortecaja ventana = new frmcortecaja();
        escritorio.add(ventana);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.toFront();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
       
        ventana.setVisible(true);  
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error: " + e);
        }
    }//GEN-LAST:event_menucortecajaActionPerformed

    private void mnucomprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnucomprasActionPerformed
         try {
          
        boolean mostrar=true;
        
        String Nombre=puntocompra.getTitle();
        for (int a=0;a<escritorio.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
        if( puntocompra.getClass().isInstance( escritorio.getComponent(a) )){
        //JOptionPane.showMessageDialog(rootPane, "La ventana "+Nombre+" que interta abrir ya está abierta, cierre la ventana actual e intente nuevamente");
        System.out.println("esta instancia, no se debe mostrar");
        puntocompra.toFront();
        escritorio.moveToFront(puntocompra);
        mostrar=false;
       
        
    }else{
        System.out.println("no lo es, puede mostrarse");
    }
}
if(mostrar){
    
        puntocompra.setSize(escritorio.getSize());
        escritorio.add(puntocompra);
        puntocompra.setTitle("Farma-Medic Caja "+ lblidcaja.getText()+ "   Le atiende:    "+lblnombretrabajador.getText());
        frmpuntocompra.lbl_idtrabajador.setText(lblidTrab.getText());
        ((javax.swing.plaf.basic.BasicInternalFrameUI)puntocompra.getUI()).setNorthPane(null);//Con esto quito el title
         puntocompra.toFront();
        puntocompra.show();   
}
           
             
             
         /*    
        frmpuntocompra ventana = new frmpuntocompra();
        escritorio.add(ventana);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.toFront();
        ventana.setSize(desktopSize.width, desktopSize.height);
        ventana.setTitle("Farma-Medic Caja "+ lblidcaja.getText()+ "   Le atiende:    "+lblnombretrabajador.getText());
        frmpuntocompra.lbl_idtrabajador.setText(lblidTrab.getText());
        ventana.setVisible(true);  
         */
        
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error: " + e);
        }
    }//GEN-LAST:event_mnucomprasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       try {
        frmpuntoconsultaventa ventana = new frmpuntoconsultaventa();
        escritorio.add(ventana);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.toFront();
        ventana.setSize(desktopSize.width, desktopSize.height);
        ((javax.swing.plaf.basic.BasicInternalFrameUI)ventana.getUI()).setNorthPane(null);//Con esto quito el title
        ventana.setTitle("Farma-Medic Caja "+ lblidcaja.getText()+ "   Le atiende:    "+lblnombretrabajador.getText());
       
        ventana.setVisible(true);  
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error: " + e);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnuptoventaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuptoventaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuptoventaMouseClicked

    private void mnuptoventaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuptoventaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuptoventaMouseEntered

    private void mnuptoventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuptoventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuptoventaActionPerformed

    private void mnuventasxidaadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuventasxidaadminActionPerformed
 try {
        frmreporteventasxdia ventana = new frmreporteventasxdia();
        escritorio.add(ventana);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.toFront();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
       
        ventana.setVisible(true);  
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error: " + e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_mnuventasxidaadminActionPerformed

    private void menusugeridocomprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusugeridocomprasActionPerformed
     try {
         Class.forName("com.mysql.jdbc.Driver");
           Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/smartpos_terminal", "root", "");
            JasperReport jr= (JasperReport)JRLoader.loadObject(frm_pruebas.class.getResource("/Reportes/Sugeridocompras.jasper"));
            Map parametros = new HashMap<String,Object>();
            logo=new javax.swing.ImageIcon(getClass().getResource("/Img/Logo/logo.jpg"));
            imagenagua=new javax.swing.ImageIcon(getClass().getResource("/Img/Logo/agua.png"));
            parametros.put("nombreagente", frminicio.lblnombretrabajador.getText());
            parametros.put("logo", logo.getImage());
            parametros.put("marcaagua", imagenagua.getImage());
            JasperPrint jp=  JasperFillManager.fillReport(jr, parametros,conexion);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
            conexion.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error: " + e);
        } 
    }//GEN-LAST:event_menusugeridocomprasActionPerformed
    
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
      try {
        boolean mostrar=true;
        String Nombre=puntoventa1.getTitle();
        for (int a=0;a<escritorio.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
        if( puntoventa1.getClass().isInstance( escritorio.getComponent(a) )){
        // JOptionPane.showMessageDialog(rootPane, "La ventana "+Nombre+" que interta abrir ya está abierta, cierre la ventana actual e intente nuevamente");
        System.out.println("esta instancia, no se debe mostrar");
        puntoventa1.toFront();
        escritorio.moveToFront(puntoventa1);
        mostrar=false;
     }else{
        System.out.println("no lo es, puede mostrarse");
    }
}
        if(mostrar){
        Dimension desktopSize = escritorio.getSize();
        puntoventa1.setSize(escritorio.getSize());
        escritorio.add(puntoventa1);
        puntoventa1.setTitle("Farma-Medic Caja "+ lblidcaja.getText()+ "   Le atiende:    "+lblnombretrabajador.getText());
        frmpuntoventa.lbl_idtrabajador.setText(lblidTrab.getText());
        frmpuntoventa.lbl_idcaja.setText(lblidcaja.getText());
        puntoventa1.setSelected(true);
        puntoventa1.requestFocus();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)puntoventa1.getUI()).setNorthPane(null);//Con esto quito el title
        }
         puntoventa1.show();
        } catch (Exception e) {
          JOptionPane.showConfirmDialog(null,"Error: " + e);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void menuventasxrangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuventasxrangoActionPerformed
       try {
      
    frmreporteventasxrango ventana = new frmreporteventasxrango();
        escritorio.add(ventana);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        ventana.toFront();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)ventana.getUI()).setNorthPane(null);
        ventana.setVisible(true);  
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error al abrir dialog: " + e);
        }
    }//GEN-LAST:event_menuventasxrangoActionPerformed

    private void menuinventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuinventarioActionPerformed
     try {
         frminventariando ventana = new frminventariando();
        escritorio.add(ventana);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = ventana.getSize();
         ventana.setSize(desktopSize.width, desktopSize.height);
        ventana.toFront();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)ventana.getUI()).setNorthPane(null);
        ventana.setVisible(true);  
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error al abrir dialog: " + e);
        }
    }//GEN-LAST:event_menuinventarioActionPerformed

    private void menuexistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuexistenciasActionPerformed
        try {
         Class.forName("com.mysql.jdbc.Driver");
           Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/smartpos_terminal", "root", "");
            JasperReport jr= (JasperReport)JRLoader.loadObject(frm_pruebas.class.getResource("/Reportes/catalogoproductos.jasper"));
            Map parametros = new HashMap<String,Object>();
            logo=new javax.swing.ImageIcon(getClass().getResource("/Img/Logo/logo.jpg"));
            imagenagua=new javax.swing.ImageIcon(getClass().getResource("/Img/Logo/agua.png"));
            parametros.put("nombreagente", frminicio.lblnombretrabajador.getText());
            parametros.put("logo", logo.getImage());
            parametros.put("marcaagua", imagenagua.getImage());
            JasperPrint jp=  JasperFillManager.fillReport(jr, parametros,conexion);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
            conexion.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error: " + e);
        }
    }//GEN-LAST:event_menuexistenciasActionPerformed

    private void menupreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupreciosActionPerformed
         try {
         Class.forName("com.mysql.jdbc.Driver");
           Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/smartpos_terminal", "root", "");
            JasperReport jr= (JasperReport)JRLoader.loadObject(frm_pruebas.class.getResource("/Reportes/catalogoproductosxprecios.jasper"));
            Map parametros = new HashMap<String,Object>();
            logo=new javax.swing.ImageIcon(getClass().getResource("/Img/Logo/logo.jpg"));
            imagenagua=new javax.swing.ImageIcon(getClass().getResource("/Img/Logo/agua.png"));
            parametros.put("nombreagente", frminicio.lblnombretrabajador.getText());
            parametros.put("logo", logo.getImage());
            parametros.put("marcaagua", imagenagua.getImage());
            JasperPrint jp=  JasperFillManager.fillReport(jr, parametros,conexion);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
            conexion.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error: " + e);
        }
    }//GEN-LAST:event_menupreciosActionPerformed

    private void menuvalorinventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuvalorinventarioActionPerformed
         try {
         Class.forName("com.mysql.jdbc.Driver");
           Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/smartpos_terminal", "root", "");
            JasperReport jr= (JasperReport)JRLoader.loadObject(frm_pruebas.class.getResource("/Reportes/INVENTARIOVALOR.jasper"));
            Map parametros = new HashMap<String,Object>();
            logo=new javax.swing.ImageIcon(getClass().getResource("/Img/Logo/logo.jpg"));
            imagenagua=new javax.swing.ImageIcon(getClass().getResource("/Img/Logo/agua.png"));
            parametros.put("nombreagente", frminicio.lblnombretrabajador.getText());
            parametros.put("logo", logo.getImage());
            parametros.put("marcaagua", imagenagua.getImage());
            JasperPrint jp=  JasperFillManager.fillReport(jr, parametros,conexion);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
            conexion.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error: " + e);
        }
    }//GEN-LAST:event_menuvalorinventarioActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
    try {
        boolean mostrar=true;
        String Nombre=puntoventa2.getTitle();
        for (int a=0;a<escritorio.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
        if( puntoventa2.getClass().isInstance( escritorio.getComponent(a) )){
        // JOptionPane.showMessageDialog(rootPane, "La ventana "+Nombre+" que interta abrir ya está abierta, cierre la ventana actual e intente nuevamente");
        System.out.println("esta instancia, no se debe mostrar");
        puntoventa2.toFront();
        escritorio.moveToFront(puntoventa2);
        mostrar=false;
     }else{
        System.out.println("no lo es, puede mostrarse");
    }
}
        if(mostrar){
        Dimension desktopSize = escritorio.getSize();
        puntoventa2.setSize(escritorio.getSize());
        escritorio.add(puntoventa2);
        puntoventa2.setTitle("Farma-Medic Caja "+ lblidcaja.getText()+ "   Le atiende:    "+lblnombretrabajador.getText());
        frmpuntoventa2.lbl_idtrabajador.setText(lblidTrab.getText());
        frmpuntoventa2.lbl_idcaja.setText(lblidcaja.getText());
        ((javax.swing.plaf.basic.BasicInternalFrameUI)puntoventa2.getUI()).setNorthPane(null);//Con esto quito el title
        }
         puntoventa2.show();
        } catch (Exception e) {
          JOptionPane.showConfirmDialog(null,"Error: " + e);
        }
       
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void menuinventario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuinventario1ActionPerformed
        try {
        frmimpresoras impresoras = new frmimpresoras();
        escritorio.add(impresoras);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = impresoras.getSize();
        impresoras.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        //impresoras.setSize(desktopSize.width, desktopSize.height);
        impresoras.toFront();
        
        impresoras.setVisible(true);  
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error al abrir dialog: " + e);
        }
    }//GEN-LAST:event_menuinventario1ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MouseClicked

    private void menuutilidadxrangoxarticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuutilidadxrangoxarticuloActionPerformed
       try {
      
    frmreporteutilidadxrango rep_utilidad = new frmreporteutilidadxrango();
        escritorio.add(rep_utilidad);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = rep_utilidad.getSize();
        rep_utilidad.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        rep_utilidad.toFront();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)rep_utilidad.getUI()).setNorthPane(null);
        rep_utilidad.setVisible(true);  
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error al abrir dialog: " + e);
        }
    }//GEN-LAST:event_menuutilidadxrangoxarticuloActionPerformed

    private void menureportesdeutilidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menureportesdeutilidadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menureportesdeutilidadMouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
       System.gc();
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void mnuptoventa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuptoventa2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuptoventa2MouseClicked

    private void mnuptoventa2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuptoventa2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuptoventa2MouseEntered

    private void mnuptoventa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuptoventa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuptoventa2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        try {
          boolean mostrar=true;
          
          String Nombre=puntopreventa.getTitle();
          for (int a=0;a<escritorio.getComponentCount();a++){     // verificar si es instancia de algun componente que ya este en el jdesktoppane
          if( puntopreventa.getClass().isInstance( escritorio.getComponent(a) )){
       // JOptionPane.showMessageDialog(rootPane, "La ventana "+Nombre+" que interta abrir ya está abierta, cierre la ventana actual e intente nuevamente");
        System.out.println("esta instancia, no se debe mostrar");
        puntopreventa.toFront();
        escritorio.moveToFront(puntopreventa);
        mostrar=false;
 
    }else{
        System.out.println("no lo es, puede mostrarse");
    }
}
if(mostrar){
    
        Dimension desktopSize = escritorio.getSize();
         puntopreventa.setSize(escritorio.getSize());
        escritorio.add(puntopreventa);
        puntopreventa.setTitle("Farma-Medic Caja "+ lblidcaja.getText()+ "   Le atiende:    "+lblnombretrabajador.getText());
          frmpuntoventa_preventa.lbl_idtrabajador.setText(lblidTrab.getText());
        frmpuntoventa_preventa.lbl_idcaja.setText(lblidcaja.getText());
          ((javax.swing.plaf.basic.BasicInternalFrameUI)puntopreventa.getUI()).setNorthPane(null);//Con esto quito el title
}
         puntopreventa.show();

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error: " + e);
        }      // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
        frmventascongeladaslista ventana = new frmventascongeladaslista();
        escritorio.add(ventana);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.toFront();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
       
        ventana.setVisible(true);  
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error: " + e);
        }  
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menureportesdecomisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menureportesdecomisionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menureportesdecomisionMouseClicked

    private void menucomisionxrangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucomisionxrangoActionPerformed
         try {
    frmreportecomisionxrango rep_utilidad = new frmreportecomisionxrango();
        escritorio.add(rep_utilidad);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = rep_utilidad.getSize();
        rep_utilidad.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        rep_utilidad.toFront();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)rep_utilidad.getUI()).setNorthPane(null);
        rep_utilidad.setVisible(true);  
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error al abrir dialog: " + e);
        }
    }//GEN-LAST:event_menucomisionxrangoActionPerformed

    private void mnuventasxida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuventasxida1ActionPerformed
 try {
        frmreportecomprasxdia ventana = new frmreportecomprasxdia();
        escritorio.add(ventana);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.toFront();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
       
        ventana.setVisible(true);  
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error: " + e);
    }          // TODO add your handling code here:
    }//GEN-LAST:event_mnuventasxida1ActionPerformed

    private void menucomprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menucomprasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menucomprasMouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            frmpv_equipaje ventana = new frmpv_equipaje();

            ventana.setTitle("Farma-Medic Caja "+ lblidcaja.getText()+ "   Le atiende:    "+lblnombretrabajador.getText());
            frmpv_equipaje.lbl_idtrabajador.setText(lblidTrab.getText());
            frmpv_equipaje.lbl_idcaja.setText(lblidcaja.getText());
            ventana.setExtendedState(frmpv_equipaje.MAXIMIZED_BOTH);
            // ((javax.swing.plaf.basic.BasicInternalFrameUI)ventana.getUI()).setNorthPane(null);//Con esto quito el title
            // ventana.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
            ventana.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error ventana equipaje: " + e);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        try {
            frmreporteequipajexrango ventana = new frmreporteequipajexrango();
            escritorio.add(ventana);
            Dimension desktopSize = escritorio.getSize();
            Dimension FrameSize = ventana.getSize();
            ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            ventana.toFront();
            ((javax.swing.plaf.basic.BasicInternalFrameUI)ventana.getUI()).setNorthPane(null);
            ventana.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error al abrir dialog: " + e);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void menuguardaequipajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuguardaequipajeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuguardaequipajeMouseClicked

    private void menucortecaja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucortecaja1ActionPerformed
        try {
            frmcaja_gastos ventana = new frmcaja_gastos();
            escritorio.add(ventana);
            Dimension desktopSize = escritorio.getSize();
            Dimension FrameSize = ventana.getSize();
            ventana.toFront();
            ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);

            ventana.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error: " + e);}
    }//GEN-LAST:event_menucortecaja1ActionPerformed

    private void menuadmoncajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuadmoncajaActionPerformed
        try {
            frmcaja_administracion ventana = new frmcaja_administracion();
            escritorio.add(ventana);
            Dimension desktopSize = escritorio.getSize();
            Dimension FrameSize = ventana.getSize();
            ventana.toFront();
            ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);

            ventana.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error: " + e);
        }
    }//GEN-LAST:event_menuadmoncajaActionPerformed

    private void menuventasxrango1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuventasxrango1ActionPerformed
       try {
    frmreporteventasxrangoxtrab ventana = new frmreporteventasxrangoxtrab();
        escritorio.add(ventana);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        ventana.toFront();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)ventana.getUI()).setNorthPane(null);
        ventana.setVisible(true);  
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error al abrir dialog: " + e);
        }
    }//GEN-LAST:event_menuventasxrango1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
try {
            frmreporteequipajexrangoxtrabajador ventana = new frmreporteequipajexrangoxtrabajador();
            escritorio.add(ventana);
            Dimension desktopSize = escritorio.getSize();
            Dimension FrameSize = ventana.getSize();
            ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            ventana.toFront();
            ((javax.swing.plaf.basic.BasicInternalFrameUI)ventana.getUI()).setNorthPane(null);
            ventana.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error al abrir dialog: " + e);
        }    
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void mnuventasxida2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuventasxida2ActionPerformed
       try {
        frmreporteventasxdiarestringido ventana = new frmreporteventasxdiarestringido();
        escritorio.add(ventana);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.toFront();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
       
        ventana.setVisible(true);  
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Error: " + e);
        }   
    }//GEN-LAST:event_mnuventasxida2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frminicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frminicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frminicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frminicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frminicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lblidTrab;
    public static javax.swing.JLabel lblidcaja;
    public static javax.swing.JLabel lblnombretrabajador;
    public static javax.swing.JLabel lbltextcaja;
    public static javax.swing.JLabel lbltexttranajador1;
    private javax.swing.JMenuBar menuBar;
    public static javax.swing.JMenuItem menuadmoncaja;
    public static javax.swing.JMenuItem menualtaexpress;
    private javax.swing.JMenuItem menuclientes;
    public static javax.swing.JMenuItem menucomisionxrango;
    public static javax.swing.JMenu menucompras;
    public static javax.swing.JMenuItem menucortecaja;
    public static javax.swing.JMenuItem menucortecaja1;
    public static javax.swing.JMenuItem menuexistencias;
    public static javax.swing.JMenu menuguardaequipaje;
    public static javax.swing.JMenuItem menuinventario;
    public static javax.swing.JMenuItem menuinventario1;
    public static javax.swing.JMenuItem menuprecios;
    public static javax.swing.JMenu menureportes;
    public static javax.swing.JMenu menureportesdecomision;
    public static javax.swing.JMenu menureportesdeutilidad;
    public static javax.swing.JMenuItem menusugeridocompras;
    public static javax.swing.JMenu menuutilerias;
    public static javax.swing.JMenuItem menuutilidadxrangoxarticulo;
    public static javax.swing.JMenuItem menuvalorinventario;
    public static javax.swing.JMenuItem menuventasxrango;
    public static javax.swing.JMenuItem menuventasxrango1;
    public static javax.swing.JMenuItem mnucompras;
    private javax.swing.JMenu mnuoperaciones;
    public static javax.swing.JMenuItem mnuproveedores;
    private javax.swing.JMenu mnuptoventa;
    private javax.swing.JMenu mnuptoventa2;
    public static javax.swing.JMenuItem mnuusuarios;
    public static javax.swing.JMenuItem mnuventasxida1;
    public static javax.swing.JMenuItem mnuventasxida2;
    public static javax.swing.JMenuItem mnuventasxidaadmin;
    private javax.swing.JMenuItem productosMenuItem;
    public static javax.swing.JLabel txtbienvenido;
    // End of variables declaration//GEN-END:variables

}
