/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.logarticulo;
import Logica.logcommon;
import java.awt.Dialog;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.security.x509.X500Name;
import Logica.CellRenderer;
import java.util.Enumeration;
import javax.swing.JTable;
import javax.swing.table.TableColumn;

/**
 *
 * @author ZAIR
 */
public class frmproductopuntoventa extends javax.swing.JInternalFrame {

    private Dialog dialogo;
    private String producto;
    private String padre;
    /**
     * Creates new form frmcobro
     */
    public frmproductopuntoventa() {
        initComponents();
       JOptionPane.showMessageDialog(null,"inicie sin dialogo");
       ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);//Con esto quito el title
    }
    
    public frmproductopuntoventa(Dialog dialogo, String producto, String padre) {
        initComponents();
        this.dialogo=dialogo;
        this.producto=producto;
        this.padre=padre;
         mostrar(producto);
         setCellRender(tablaproducto);
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);//Con esto quito el title
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaproducto = new javax.swing.JTable();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        tablaproducto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tablaproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaproductoMouseClicked(evt);
            }
        });
        tablaproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaproductoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaproductoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablaproducto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
     public void setCellRender(JTable table) {
        Enumeration<TableColumn> en = table.getColumnModel().getColumns();
        while (en.hasMoreElements()) {
            TableColumn tc = en.nextElement();
            tc.setCellRenderer(new CellRenderer());
        }
    }
     void formatodetabla(){
    //Columnaid
    
    tablaproducto.getColumnModel().getColumn(0).setPreferredWidth(300);
    //Columna descripcion
    tablaproducto.getColumnModel().getColumn(1).setPreferredWidth(500);
    //colunma marca
    tablaproducto.getColumnModel().getColumn(2).setPreferredWidth(100);
    //Columna tipo
    tablaproducto.getColumnModel().getColumn(3).setMaxWidth(0);
    tablaproducto.getColumnModel().getColumn(3).setMinWidth(0);
    tablaproducto.getColumnModel().getColumn(3).setPreferredWidth(0);
    //Columna impuesto
    tablaproducto.getColumnModel().getColumn(4).setMaxWidth(0);
    tablaproducto.getColumnModel().getColumn(4).setMinWidth(0);
    tablaproducto.getColumnModel().getColumn(4).setPreferredWidth(0);
    //Columna precio compra
    tablaproducto.getColumnModel().getColumn(5).setMaxWidth(0);
    tablaproducto.getColumnModel().getColumn(5).setMinWidth(0);
    tablaproducto.getColumnModel().getColumn(5).setPreferredWidth(0);
    //Columna precio venta1
    tablaproducto.getColumnModel().getColumn(6).setPreferredWidth(150);
     //Columna precio venta2
    tablaproducto.getColumnModel().getColumn(7).setPreferredWidth(150);
     //Columna precio venta3
    tablaproducto.getColumnModel().getColumn(8).setPreferredWidth(150);
     //Columna precio venta4
    tablaproducto.getColumnModel().getColumn(9).setPreferredWidth(150);
     //Columna precio venta5
    tablaproducto.getColumnModel().getColumn(10).setPreferredWidth(150);
     //Columna  imagen
    tablaproducto.getColumnModel().getColumn(11).setMaxWidth(0);
    tablaproducto.getColumnModel().getColumn(11).setMinWidth(0);
    tablaproducto.getColumnModel().getColumn(11).setPreferredWidth(0);
    //Columna  existencia
    tablaproducto.getColumnModel().getColumn(12).setPreferredWidth(50);
     //Columna  minimo
    tablaproducto.getColumnModel().getColumn(13).setMaxWidth(0);
    tablaproducto.getColumnModel().getColumn(13).setMinWidth(0);
    tablaproducto.getColumnModel().getColumn(13).setPreferredWidth(0);
     //Columna  maximo
    tablaproducto.getColumnModel().getColumn(14).setMaxWidth(0);
    tablaproducto.getColumnModel().getColumn(14).setMinWidth(0);
    tablaproducto.getColumnModel().getColumn(14).setPreferredWidth(0);
     //Columna  observaciones
    tablaproducto.getColumnModel().getColumn(15).setPreferredWidth(0);
     //Columna  fecha
    tablaproducto.getColumnModel().getColumn(16).setMaxWidth(0);
    tablaproducto.getColumnModel().getColumn(16).setMinWidth(0);
    tablaproducto.getColumnModel().getColumn(16).setPreferredWidth(0);
     //Columna  Hora
    tablaproducto.getColumnModel().getColumn(17).setMaxWidth(0);
    tablaproducto.getColumnModel().getColumn(17).setMinWidth(0);
    tablaproducto.getColumnModel().getColumn(17).setPreferredWidth(0);
     //Columna  Peso
    tablaproducto.getColumnModel().getColumn(18).setMaxWidth(0);
    tablaproducto.getColumnModel().getColumn(18).setMinWidth(0);
    tablaproducto.getColumnModel().getColumn(18).setPreferredWidth(0);
    }
    
     void mostrar(String buscar){
        try {
            DefaultTableModel modelo;
            logarticulo func = new logarticulo();
            modelo=func.mostrar(buscar);
            tablaproducto.setModel(modelo);
            formatodetabla();
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, e);
        }
    }
    
    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formMouseReleased

    private void tablaproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaproductoMouseClicked
        if (evt.getClickCount()==2 ) {
            try {
                int fila= tablaproducto.rowAtPoint(evt.getPoint());
                if (padre=="puntoventa") {
                    frmpuntoventa.txtbuscar.setText(tablaproducto.getValueAt(fila, 0).toString());
                    
                }
                if (padre=="puntoventa2") {
                    frmpuntoventa2.txtbuscar.setText(tablaproducto.getValueAt(fila, 0).toString());
                }
                

                dialogo.dispose();   
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_tablaproductoMouseClicked

    private void tablaproductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaproductoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaproductoKeyPressed

    private void tablaproductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaproductoKeyReleased
 if (evt.getKeyCode() == evt.VK_ENTER){
  try {
                int fila= tablaproducto.getSelectedRow();
                if (padre=="puntoventa") {
                    frmpuntoventa.txtbuscar.setText(tablaproducto.getValueAt(fila, 0).toString());
                    
                }
                if (padre=="puntoventa2") {
                    frmpuntoventa2.txtbuscar.setText(tablaproducto.getValueAt(fila, 0).toString());
                }
                

                dialogo.dispose();   
            } catch (Exception e) {
            }
 }        
 if (evt.getKeyCode() == evt.VK_ESCAPE){
 dialogo.dispose();
 }
    }//GEN-LAST:event_tablaproductoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaproducto;
    // End of variables declaration//GEN-END:variables
}
