/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.BorderFactory;
import javax.swing.JRootPane;
import javax.swing.border.EtchedBorder;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author ZAIR
 */
public class frmprincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmprincipal
     */
    public frmprincipal() {
        initComponents();
        //Maximizando
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("Farma-Medic");
        
        //Obtiene el tamaño de la pantalla
         Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        //obtiene la resolucion de la pantalla en PPP (Puntos por pulgada)
        int sr = Toolkit.getDefaultToolkit().getScreenResolution();
        //muestra la informacion por la consola de java
         JOptionPane.showConfirmDialog(null,"Tamaño de pantalla: " + d.width + "x" + d.height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PbtPOS = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Pbtoperaciones = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        imgoperaciones = new javax.swing.JLabel();
        Pbtninicio2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        imginventario = new javax.swing.JLabel();
        Pbtninicio3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        imgreportes = new javax.swing.JLabel();
        escritorioprueba = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(181, 222, 156));

        PbtPOS.setBackground(new java.awt.Color(181, 222, 156));
        PbtPOS.setPreferredSize(new java.awt.Dimension(150, 100));
        PbtPOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PbtPOSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PbtPOSMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PbtPOSMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(8, 153, 173));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Punto de Venta");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/64x64/POS.png"))); // NOI18N

        javax.swing.GroupLayout PbtPOSLayout = new javax.swing.GroupLayout(PbtPOS);
        PbtPOS.setLayout(PbtPOSLayout);
        PbtPOSLayout.setHorizontalGroup(
            PbtPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PbtPOSLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(92, 92, 92))
        );
        PbtPOSLayout.setVerticalGroup(
            PbtPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PbtPOSLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        Pbtoperaciones.setBackground(new java.awt.Color(181, 222, 156));
        Pbtoperaciones.setPreferredSize(new java.awt.Dimension(150, 100));
        Pbtoperaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PbtoperacionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PbtoperacionesMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PbtoperacionesMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(8, 153, 173));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Operacionés");

        imgoperaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/64x64/operaciones.png"))); // NOI18N

        javax.swing.GroupLayout PbtoperacionesLayout = new javax.swing.GroupLayout(Pbtoperaciones);
        Pbtoperaciones.setLayout(PbtoperacionesLayout);
        PbtoperacionesLayout.setHorizontalGroup(
            PbtoperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PbtoperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PbtoperacionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgoperaciones)
                .addGap(95, 95, 95))
        );
        PbtoperacionesLayout.setVerticalGroup(
            PbtoperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PbtoperacionesLayout.createSequentialGroup()
                .addComponent(imgoperaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pbtninicio2.setBackground(new java.awt.Color(181, 222, 156));
        Pbtninicio2.setPreferredSize(new java.awt.Dimension(150, 100));
        Pbtninicio2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pbtninicio2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pbtninicio2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pbtninicio2MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(8, 153, 173));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Inventario");

        imginventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/64x64/inventario.png"))); // NOI18N

        javax.swing.GroupLayout Pbtninicio2Layout = new javax.swing.GroupLayout(Pbtninicio2);
        Pbtninicio2.setLayout(Pbtninicio2Layout);
        Pbtninicio2Layout.setHorizontalGroup(
            Pbtninicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Pbtninicio2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(imginventario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Pbtninicio2Layout.setVerticalGroup(
            Pbtninicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pbtninicio2Layout.createSequentialGroup()
                .addComponent(imginventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Pbtninicio3.setBackground(new java.awt.Color(181, 222, 156));
        Pbtninicio3.setPreferredSize(new java.awt.Dimension(150, 100));
        Pbtninicio3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pbtninicio3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Pbtninicio3MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pbtninicio3MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(8, 153, 173));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Reportes");

        imgreportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/64x64/reportes.png"))); // NOI18N

        javax.swing.GroupLayout Pbtninicio3Layout = new javax.swing.GroupLayout(Pbtninicio3);
        Pbtninicio3.setLayout(Pbtninicio3Layout);
        Pbtninicio3Layout.setHorizontalGroup(
            Pbtninicio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Pbtninicio3Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(imgreportes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Pbtninicio3Layout.setVerticalGroup(
            Pbtninicio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pbtninicio3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgreportes, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pbtoperaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addComponent(Pbtninicio3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addComponent(Pbtninicio2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addComponent(PbtPOS, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(PbtPOS, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pbtoperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Pbtninicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(Pbtninicio3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout escritoriopruebaLayout = new javax.swing.GroupLayout(escritorioprueba);
        escritorioprueba.setLayout(escritoriopruebaLayout);
        escritoriopruebaLayout.setHorizontalGroup(
            escritoriopruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1066, Short.MAX_VALUE)
        );
        escritoriopruebaLayout.setVerticalGroup(
            escritoriopruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorioprueba))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(escritorioprueba)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Pbtninicio3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pbtninicio3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pbtninicio3MousePressed

    private void Pbtninicio3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pbtninicio3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Pbtninicio3MouseEntered

    private void Pbtninicio3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pbtninicio3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Pbtninicio3MouseClicked

    private void Pbtninicio2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pbtninicio2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pbtninicio2MousePressed

    private void Pbtninicio2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pbtninicio2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Pbtninicio2MouseEntered

    private void Pbtninicio2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pbtninicio2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Pbtninicio2MouseClicked

    private void PbtoperacionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PbtoperacionesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PbtoperacionesMousePressed

    private void PbtoperacionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PbtoperacionesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PbtoperacionesMouseEntered

    private void PbtoperacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PbtoperacionesMouseClicked
        frmprincipalreportes reportes = new frmprincipalreportes();
        escritorioprueba.add(reportes);
        reportes.setVisible(true);
        //reportes.setLocationRelativeTo(escritorio);
        //reportes.setBounds(245, 23, this.escritorio.getWidth()-125, this.escritorio.getHeight());
        //PbtPOS.setBackground(new Color(8, 99, 173) );
        Pbtoperaciones.setBorder(BorderFactory.createEtchedBorder());
        
    }//GEN-LAST:event_PbtoperacionesMouseClicked

    private void PbtPOSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PbtPOSMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_PbtPOSMousePressed

    private void PbtPOSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PbtPOSMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_PbtPOSMouseEntered

    private void PbtPOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PbtPOSMouseClicked
        // TODO add your handling code here:
        
        frmpuntoventa puntoventa = new frmpuntoventa();
        puntoventa.setVisible(true);
       
       // puntoventa.setLocationRelativeTo(this.escritorioprueba);
        puntoventa.setBounds(245, 23, this.escritorioprueba.getWidth(), this.escritorioprueba.getHeight());
       
        //PbtPOS.setBackground(new Color(8, 99, 173) );
        PbtPOS.setBorder(BorderFactory.createEtchedBorder());
    }//GEN-LAST:event_PbtPOSMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PbtPOS;
    private javax.swing.JPanel Pbtninicio2;
    private javax.swing.JPanel Pbtninicio3;
    private javax.swing.JPanel Pbtoperaciones;
    private javax.swing.JDesktopPane escritorioprueba;
    private javax.swing.JLabel imginventario;
    private javax.swing.JLabel imgoperaciones;
    private javax.swing.JLabel imgreportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
